# Generated by Django 4.2.3 on 2023-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cbal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
