# Generated by Django 4.2.3 on 2023-08-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_customer_cbal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cbal',
            field=models.CharField(max_length=15),
        ),
    ]
